version: '3.9'
services:
  proxy:
    image: proxy
    container_name: proxy
    build: ./proxy
    ports:
      - 80:80
    restart: always
  next:
    image: next
    container_name: next
    build: ./frontend2
    ports:
      - 3000
    restart: always
    depends_on:
      - proxy
  keystone:
    image: keystone
    container_name: keystone
    build: ./keystone
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - 3000
    # restart: always
    depends_on:
      - proxy
  # pgadmin:
  #   container_name: pgadmin
  #   image: pgadmin
  #   build: ./pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - '5050:80'
  # frontend:
  #   image: frontend
  #   container_name: frontend
  #   build: ./frontend2
  #   ports:
  #     - 3000
  #   restart: always
  #   depends_on:
  #     - proxy
  # backend:
  #   image: backend
  #   container_name: backend
  #   build: ./backend2
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     SESSION_SECRET: ${SESSION_SECRET}
  #   ports:
  #     - 3000
  #   restart: always
  #   depends_on:
  #     - proxy
