name: Sick Fits Preview Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Login
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Create namespace
        uses: okteto/create-namespace@latest
        with:
          namespace: pr-${{ github.event.number }}-bronifty

      - name: Deploy application
        uses: okteto/deploy-stack@latest
        with:
          build: 'true'
          namespace: pr-${{ github.event.number }}-bronifty
          token: ${{ secrets.DATABASE_URL }}
